-- 检查数据库外键约束
-- 使用这个脚本查看所有外键约束

-- 查看所有外键约束
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE 
    TABLE_SCHEMA = DATABASE() 
    AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY 
    TABLE_NAME, CONSTRAINT_NAME;

-- 查看特定表的外键约束
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE 
    TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'stage_progress' OR REFERENCED_TABLE_NAME = 'stage_progress')
    AND REFERENCED_TABLE_NAME IS NOT NULL;

-- 查看stage_progress表结构
DESCRIBE stage_progress;

-- 查看projects表结构
DESCRIBE projects;